TF_VAR_PERSONAL_ACCESS_TOKEN="${PERSONAL_ACCESS_TOKEN}" TF_VAR_REPO_OWNER="${REPO_OWNER}" TF_VAR_REPO_NAME="${REPO_NAME}" TF_VAR_AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" TF_VAR_AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" TF_VAR_AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" terraform apply -auto-approve

